[build-system]
requires = [
    "setuptools>=61",
    "numpy>=1.9.1",
    "cython>=0.29",
]
build-backend = "setuptools.build_meta"


[project]
name = "pyEDFlib"
maintainers = [
    { name = "Holger Nahrstaedt", email = "nahrstaedt@gmail.com" },
]
authors = [
    { name = "Holger Nahrstaedt", email = "nahrstaedt@gmail.com" },
]
description = "library to read/write EDF+/BDF+ files"
readme = "README.rst"
license = { text = "BSD" }
requires-python = ">=3.9"
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Intended Audience :: Developers",
    "Intended Audience :: Education",
    "Intended Audience :: Science/Research",
    "License :: OSI Approved :: BSD License",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: Implementation :: CPython",
    "Programming Language :: C",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
    "Topic :: Software Development :: Libraries :: Python Modules",
]
keywords = [
    "EDFlib",
    "European data format",
    "EDF",
    "BDF",
    "EDF+",
    "BDF+",
]
dynamic = ["version"]
dependencies = [
    "numpy>=1.9.1",
]

[project.urls]
Homepage = "https://github.com/holgern/pyedflib"


[tool.setuptools]
platforms = ["Windows", "Linux", "Solaris", "Mac OS-X", "Unix"]
packages = [
    "pyedflib",
    "pyedflib._extensions",
    "pyedflib.data",
    "pyedflib.tests",
    "pyedflib.tests.data",
]

[tool.setuptools.package-data]
"pyedflib.data" = ["*.edf", "*.bdf"]
"pyedflib.tests.data" = ["*.edf", "*.bdf"]
"pyedflib._extensions" = ["*.pyi"]

[tool.setuptools.exclude-package-data]
"pyedflib._extensions" = ["*.pyx", "*.pxd", "*.pxi", "*.c", "*.h"]


[tool.ruff]
line-length = 110

[tool.ruff.lint]
extend-select = [
    "B",    # flake8-bugbear
    "C4",   # flake8-comprehensions
    "ISC",  # flake8-implicit-str-concat
    "PIE",  # flake8-pie
    "PYI",  # flake8-pyi
    "FLY",  # flynt
    "I",    # isort
    "PERF", # Perflint
    "UP",   # pyupgrade
    "RUF",  # Ruff-specific rules
]
ignore = [
    "S110",    # `try`-`except`-`pass` detected, consider logging the exception
    "BLE001",  # Do not catch blind exception: `Exception`
    "SIM117",  # Use a single `with` statement with multiple contexts instead of nested `with` statements
    "B028",    # No explicit `stacklevel` keyword argument found
    "DTZ001",  # `datetime.datetime()` called without a `tzinfo` argument
    "DTZ005",  # `datetime.datetime.now()` called without a `tz` argument
    "DTZ007",  # Naive datetime constructed using `datetime.datetime.strptime()` without %z
    "FA100",   # Add `from __future__ import annotations` to simplify `typing`
    "ISC002",  # Implicitly concatenated string literals over multiple lines
    "PYI041",  # Use `float` instead of `int | float`
    "PERF203", # `try`-`except` within a loop incurs performance overhead
    "RUF003",
    "RUF005",  # Consider iterable unpacking instead of concatenation
]

[tool.ruff.lint.extend-per-file-ignores]
"**/__init__.py" = ["F401", "F403"]
