name: Lint
on:
  pull_request:
    branches:
      - '*'
permissions:
  contents: read
jobs:
  ruff:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v4
      - uses: astral-sh/ruff-action@v3
      - name: Lint with Ruff
        run: ruff check --output-format=github
